### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yoshizooo** [yoshizooo/protospace-38868#1]
https://protospace-38868.onrender.com

**Comment by snkw-works** [comment]
@yoshizooo さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### プロトタイプ詳細表示機能
- [ ] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されているよう修正しましょう**
「プロトタイプ名」が正しく表示されない状態です。
<img width="607" alt="スクリーンショット 2023-03-19 9 50 44" src="https://user-images.githubusercontent.com/54050089/226147877-29203873-1e82-41a5-8c67-2711d59c0e0e.png">

#### ユーザー詳細機能
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
・一覧の投稿者名をクリックすると、ユーザー詳細ページではなくプロトタイプ詳細ページに遷移してしまいます。
・コメントの投稿者名をクリックしたとき、そのユーザーではなくプロトタイプ投稿者のページに遷移してしまいます。
![スクリーンショット_2023-03-19_9_53_18](https://user-images.githubusercontent.com/54050089/226148089-cd26f291-4e38-4794-8bef-cbad69417305.jpg)
![スクリーンショット_2023-03-19_10_00_01](https://user-images.githubusercontent.com/54050089/226148092-358493f2-9a46-4cb4-85b3-273957bc437f.jpg)

#### その他
- [ ] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるよう修正しましょう**
ログアウト状態のユーザーが「プロトタイプ編集ページ」に遷移しようとすると、ログインページではなくトップページに遷移してしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yoshizooo** [comment]
修正しました。
お手数ですが、レビューお願いします。
https://protospace-38868.onrender.com

**Comment by snkw-works** [comment]
@yoshizooo さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について一部を除き修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメントの投稿者名をクリックしたとき、そのユーザーではなくプロトタイプ投稿者のページに遷移してしまいます。
例：「テストユーザー2」をクリックしていますが、「ユーザー1」のページに遷移してしまいます。
![スクリーンショット_2023-03-19_10_00_01](https://user-images.githubusercontent.com/54050089/226148092-358493f2-9a46-4cb4-85b3-273957bc437f.jpg)


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yoshizooo** [comment]
修正しました。
レビューお願いします。
https://protospace-38868.onrender.com

**Comment by motomuun** [comment]
@yoshizooo さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
